eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 950530
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 119.29.198.89
    port: 5672
    username: guest
    password: guest

server:
  port: 8081
